### ISSUE TITLE
Data cannot be shared between static methods

### ISSUE THREAD

**Issue by edeca** [sciapp/flask-restful-hal#1]
The basic example shows how flask-restful-hal uses static methods:

```
class Todo(Resource):
    @staticmethod
    def data(todo):
        return TODOS[todo]
```

Some functions will need to implement `data(..)`, `links(..)` and `embedded(..)`.  Code in `get()` will often fetch information from a backend store, e.g. a database.  However, the use of static methods means that data cannot easily be shared between each function.

Is there a nicer way of sharing data than putting it in the global `g` variable?

**Comment by edeca** [comment]
Understood that invocation order may change in future.  However, it's not sensible to repeat a database call and it feels incorrect to store data in `g` or any other global variable.  There needs to be some way for data to be shared across all functions.

Do they need to be three separate functions?  Could `data()` be refactored to something like:

```
class Todo(Resource):
    def data(self, .. args .., embed=True, links=False):
        embedded = None
        link_data = None

        # Fetch data
        my_data = my_db.get_some_todos()

        if embed:
            # create a set of Embedded() objects
            arguments_list = ... 
            embedded = Embedded('items', Todo, *arguments_list)

        if links:
            # Make a list of links

        # Return tuple of (data, embedded data, links)
        return (my_data, embedded, link_data)
```

This would also solve another query I had, how to make embedded objects default for certain endpoints.  The implementation can set the default in the kwargs of `data()`.

Or could the static requirement be dropped, allowing access to `self` and class variables?

**Comment by IngoHeimbach** [comment]
You are right, it should not be necessary to repeat database access three times if data can be fetched in one run. I never ran into this issue because the application that uses flask-restful-hal has a global data storage object with internal caching so querying data multiple times was not an issue.

The methods `data`, `embedded` and `links` are called as class methods currently (see [resource.py, line 177](https://github.com/sciapp/flask-restful-hal/blob/v0.1.6/flask_restful_hal/resource.py#L177) for an example). But I could call the methods on `self` instead, so `data`, `embedded` and `links` could be implemented as normal instance methods (but static methods are still legal so existing code does not break).

In general, it would be great to stay compatible to existing code and in my opinion using three separate methods is quite convenient for many cases but your suggestion to put everything into one method gives better control. Maybe the package can offer both ways. I think about something like this:

1. Using separate methods:
    Implement `data`, `embedded`, `links` and an optional method `pre_hal` that is called before the first three ones. This method could be used to fetch data from a database and store it in an instance attribute.
2. Using one method:
    Implement a single method (could be named `get_hal` for example) that handles data, embedded and links at once like you suggested. 

flask-restful-hal would inspect the implemented resource class to determine which methods are actually implemented.

**Comment by edeca** [comment]
Tried the feature/data-share branch tonight but ran into trouble around [resource.py line 55](https://github.com/sciapp/flask-restful-hal/blob/feature/data-share/flask_restful_hal/resource.py#L55) when embedding data.  The input string is used as `self` [here](https://github.com/sciapp/flask-restful-hal/blob/feature/data-share/flask_restful_hal/resource.py#L128), which causes an exception.

**Comment by IngoHeimbach** [comment]
@edeca The problem should be solved now. Could you test the feature again? If everything works, I will publish a new release.

**Comment by edeca** [comment]
Looks good now.  Simple PoC below that will print to the console.

~~~python
class TestList(HalResource):
    def pre_hal(self, embed=True, include_links=True):
        print("In pre-hal!")
        self.foo = "wibble"

    def data(self):
        print("In data")
        print("self.foo is {}".format(self.foo))

    def embed(self):
        print("In embed")
        print("self.foo is {}".format(self.foo))
~~~

**Comment by IngoHeimbach** [comment]
[v0.2.0 is online on PyPI](https://pypi.org/project/flask-restful-hal/0.2.0/). 😊

**Comment by edeca** [comment]
Thanks Ingo.  Have just noticed another issue.  It's possible to return a list of embedded objects from an object, e.g. from `TodoList`:

```python
return Embedded('items', Todo, *items)
```

This will call `data()` from the `Todo` class.  However the `Todo` class has no access to the data.  It seems the global data object + cache you mention is the only way to use the module easily.

No need to reopen this ticket, but worth considering for a future release if possible.

**Comment by IngoHeimbach** [comment]
Ah, good point. Hmm, in your example the `pre_hal` feature is broken completely since it is only called when a resource is directly acquired by a `GET` request. Maybe `pre_hal` should be called every time when a resource object is instantiated?
